name: Generate ASCII artwork

on:
    push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Cowsay program
      uses: sudo apt -get install cowsay -y

    - name: Execute cowsay cmd
      uses: cowsay -f dragon "Run for cover, I am DRAGON...RAWR" >> dragon.txt

    - name: Test File Exists
      uses: grep -i "dragon" dragon.txt

    - name: Read file
      uses: cat dragon.txt

    - name: list Repo Files
      uses: ls -ltra
      